version: "3.7"

services: 
  database_bethehero:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app_bethehero:
    build: .
    restart: always
    ports: 
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - database_bethehero
    depends_on: 
      - database_bethehero

volumes:
  pgdata: 
    driver: local